# config.yaml

bronze_path: "data/bronze/"
silver_path: "data/silver/"
gold_path: "data/gold/"
hist_path: "data/hist/"

providers:
  provider1:
    subpath: "provider1/"
    periodicity: "weekly"
    format: "csv"
    primary_key: ["movie_title","release_year"]
    mapping:
      movie_title: movie_title
      release_year: release_year
      critic_score_percentage: critic_score_percentage
      top_critic_score: top_critic_score
      total_critic_reviews_counted: total_critic_reviews_counted

  provider2:
    subpath: "provider2/"
    periodicity: "twice_a_month"
    format: "json"
    primary_key: ["title","year"]
    mapping:
      title: movie_title
      year: release_year
      audience_average_score: audience_average_score
      total_audience_ratings: total_audience_ratings
      domestic_box_office_gross: domestic_box_office_gross

  provider3:
    subpath: "provider3/"
    periodicity: "monthly"
    format: "csv"
    primary_key: ["film_name","year_of_release"]
    mapping:
      film_name: movie_title
      year_of_release: release_year
      domestic_box_office_usd: domestic_box_office_usd
      international_box_office_usd: international_box_office_usd 
      production_budget_usd: production_budget_usd
      marketing_spend_usd: marketing_spend_usd 

    file_level_renames:
      - match_glob: "**/provider3_domestic.csv"     
        rename:
          box_office_gross_usd: domestic_box_office_usd
      - match_glob: "**/provider3_international.csv" 
        rename:
          box_office_gross_usd: international_box_office_usd         

casts:
  movie_title: string
  release_year: int
  critic_score_percentage: float
  top_critic_score: float
  total_critic_reviews_counted: int
  audience_average_score: float
  total_audience_ratings: int
  domestic_box_office_gross: int
  domestic_box_office_usd: int
  international_box_office_usd: int
  production_budget_usd: int
  marketing_spend_usd: int

silver_data_format: "parquet"
gold_data_format: "parquet"

gold_primary_key: ["movie_title", "release_year"]